// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5luIw5H83EXByAcfSkC_UcSGDoQNzADQ',
    appId: '1:178608639812:web:d4b98fa0ee1b9ab574d111',
    messagingSenderId: '178608639812',
    projectId: 'serhii-hrabas',
    authDomain: 'serhii-hrabas.firebaseapp.com',
    databaseURL:
        'https://serhii-hrabas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serhii-hrabas.firebasestorage.app',
    measurementId: 'G-44355B5T6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDODlUIwPfV9c1hX-m2iLF3A2yC5dam4FU',
    appId: '1:178608639812:android:e8aacdc1e658e2a474d111',
    messagingSenderId: '178608639812',
    projectId: 'serhii-hrabas',
    databaseURL:
        'https://serhii-hrabas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serhii-hrabas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfZxOtM7sJnr6Yv3s47dyO02_Bpj4K2X4',
    appId: '1:178608639812:ios:302b23c862cc4c1d74d111',
    messagingSenderId: '178608639812',
    projectId: 'serhii-hrabas',
    databaseURL:
        'https://serhii-hrabas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serhii-hrabas.firebasestorage.app',
    iosBundleId: 'com.insearching.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfZxOtM7sJnr6Yv3s47dyO02_Bpj4K2X4',
    appId: '1:178608639812:ios:302b23c862cc4c1d74d111',
    messagingSenderId: '178608639812',
    projectId: 'serhii-hrabas',
    databaseURL:
        'https://serhii-hrabas-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serhii-hrabas.firebasestorage.app',
    iosBundleId: 'com.insearching.portfolio',
  );
}
